os: linux
dist: xenial
language: csharp
dotnet: 3.1.201
mono: none
env:
  global: 
    - REPO_OWNER=$(echo $TRAVIS_BUILD_DIR | sed -r 's/\/.+//g')
  jobs:
    - RUNTIME=win-x64 OUTPUT_TYPE=Exe SELF_CONTAINED=false
    - RUNTIME=win-x64 OUTPUT_TYPE=Exe SELF_CONTAINED=true
    - RUNTIME=linux-x64 OUTPUT_TYPE=Exe SELF_CONTAINED=false
    - RUNTIME=linux-x64 OUTPUT_TYPE=Exe SELF_CONTAINED=true
before-install:
  - cd ~/build/${REPO_OWNER} && git clone https://github.com/clarkx86/common_ci-scripts.git && cd common_ci-scripts
  - git checkout c1efd24ae26fd572cdc03575d3da5e0f588a9e43
  - chmod +x ./*
  - REPO_NAME=$(./get_repo-name.sh $TRAVIS_REPO_SLUG)
  - TAG_CLEAN=$(./get_tag_clean.sh $(echo $TRAVIS_TAG | sed -E 's/\s\w+//')
  - ASSEMBLY_VERSION=$(./format_assembly-version.sh $TAG_CLEAN $TRAVIS_BUILD_NUMBER)
before-script:
  - cd ~/build/${TRAVIS_REPO_SLUG}/src
script:
  - ARTIFACT_SUFFIX=$(if [ "$SELF_CONTAINED" == "true" ]; then echo "-bundled"; elif [ "$OUTPUT_TYPE" == "Library" ]; then echo "-lib"; else echo ""; fi)
  - ARTIFACT_NAME=${REPO_NAME}_${RUNTIME}${ARTIFACT_SUFFIX}_v${TAG_CLEAN}-${TRAVIS_BUILD_NUMBER}
  - VERSION_SUFFIX=$(echo $TRAVIS_TAG | sed -E 's/.+\s//')
  - dotnet publish vellum.csproj -c Release -r ${RUNTIME} /property:Version=${ASSEMBLY_VERSION} /property:OutputType=${OUTPUT_TYPE} /p:PublishTrimmed=${SELF_CONTAINED} --self-contained ${SELF_CONTAINED} $(if [[ ! -z $VERSION_SUFFIX ]]; then echo "/p:DefineConstants=\"$(echo $VERSION_SUFFIX | tr [:lower:] [:upper:])\""; fi)
before_deploy:
  - cd bin/Release/netcoreapp3.1/${RUNTIME}/publish && zip ${ARTIFACT_NAME}.zip ./*
  - wget -q https://github.com/${TRAVIS_REPO_SLUG}/releases/download/${TRAVIS_TAG}/sha256sums.txt || true
  - sha256sum ${ARTIFACT_NAME}.zip >> sha256sums.txt
deploy:
  provider: releases
  token:
    secure: "bkpf8FnXooiKvbjgm/5kFV6y+5Apgi6sQm1iIdOfRTF4dkAdJG/p0fATFoR1V8HINIF9gN2bV7HefQz3UbgspbawPE/DK+HcHj1gHSjZ7QiabTSX4PgM5KfV0q54abIyot5kfyf+fj5RRrEsARFeDVpIi+B/VnyKJKb+5X9uTG8CzS1w4Afacjfh4gGFAW1aBAue/Oii96u42SZGk/gDX62kYUoiG1RXcx8acYSJOG241RfqiXN3zxZorhxItBLlAJUdC9n2FXPVw9awi/Joc643SE8TdBcqcggLKBieX8NVIk1YPIipanPZsubGafje78cqiMVquAxpq3BBamJEzKy4UPbW9SzI9/pkQtDuoaG6RvbtEjobKVKsKLeaP/uXE3fVorTeIpdNKmqkbag9yG0gOMu6JHkfEZCOHDBQXYSo22bevzO9dcWP8VmYwreaiUfYoZB3i+VEvZHH1k3ymEr4ckKchrg+/Enkj1SwzdDNdgl6PWsVt6Di+I8IMSMQ/Zqh3p6IhFWaX6WwIMbGcK2wkN1eqGg/aGfXCHoTatBi55zRYfvY3NlMzkuHX7Gn1Bf7Su6GR4NfBD7PbweQDI6dXO5bqfst9Dvq2a57SaDeRBzKtrPHWZ50ri3ppImucIUZmus4dCJlJSr2f1FVublzF2lI7EJI3u5eb8f7KH4="
  file:
    - ${ARTIFACT_NAME}.zip
    - sha256sums.txt
  overwrite: true
  skip_cleanup: true
  on:
    repo: clarkx86/vellum
    tags: true
jobs:
  include:
    - if: tag IS present
      env:
        - secure: "QrNeuR+zCypZYVdECiIST4/vGPUCEmrPgu8BxuvX4ODYkPRai8YSAC1tEe075p2rcibnRcTL9Z2qz6C1zddGRtPM5YJZXU6u9beJB6Lr0rYOXCWeEEOmHSrAK6bH6gQDFMTnVMTErIJXImf+pJ9IkWDxetnR5W9Sc+rDvDWu0CNqizyypFXWtpNnYVgZ4jvwo67RSLAHxK9JmGUGpzzmqSxLAf5EwS1WXm5kjWLkmxsIGm6LfKvlWJkc/DWUGlxdZz56PXb6oOBhTHiHTTZ8POFN4y0o/znYB7JWFnv8No2xmi9nqep5RbT3tntgDTBJzbCCYMn8n/0X54P8r3wTNBaGfWTpsKcJbsMUEpHXw1+4U+J/fSKNTgvHwtryZqqrK9ZNaPm2c+eBBwXuHgyTTva5xcQ8YpXa08VfHXoi0ebEepLgPUl6Yc5UGH5+9NAHZimScszFF9TSn8Yw+UWo2NN4ihn2ISmmZpmXZpsr80cwZ27qPDrEmCnNl7v4AUaeq368y+QniKZBQJR9XPVblGnRDClXk5TNDryMEIXdAbHgMp2aMpg4UtavACqUlJCoMimTPpwCksmM/8X/wgv4gWHv9VmV4SRrxG9yg5qmkFazdoQDWcXUh8tgoV7Bw3oraIHFQvz5ihKjmh84hK7yDBdFGOAuH9YMi94VjV/8jpw="
        - OUTPUT_TYPE=Library
      script:
        - ARTIFACT_NAME=${REPO_NAME}.${TAG_CLEAN}
        - dotnet pack -c Release /property:Version=${TAG_CLEAN} /property:OutputType=${OUTPUT_TYPE}
      before_deploy:
        - echo '<?xml version="1.0" encoding="utf-8"?><configuration></configuration>' >> nuget.config
        - dotnet nuget add source "https://nuget.pkg.github.com/clarkx86/index.json" --configfile "nuget.config" -n "github" -u "clarkx86" -p "${GITHUB_TOKEN}" --store-password-in-clear-text
      deploy:
        provider: script
        skip_cleanup: true
        script: dotnet nuget push "bin/Release/${ARTIFACT_NAME}.nupkg" -s "github"
        on:
          repo: clarkx86/vellum
          branch: master
          tags: true
      after_script:
        - rm -f nuget.config